name: NPM Publish

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  npm-publish:
    name: NPM Publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          package-manager-cache: false

      - run: npm ci

      - run: npm run build

      - run: npm publish