name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  USE_NIGHTLY: false

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest

    steps:
    - uses: actions/checkout@v5

    - name: Set up Node
      uses: actions/setup-node@v5
      with:
        node-version: 18

    - name: npm ci
      run: npm ci

    - name: Run tests (Release)
      if: env.USE_NIGHTLY != 'true'
      run: npm test

    - name: Install Bicep (Nightly)
      if: env.USE_NIGHTLY == 'true' && runner.os == 'Windows'
      run: iex "& { $(irm https://aka.ms/bicep/nightly-cli.ps1) } -BinaryPath ${{ runner.temp }}"
      env:
        GH_TOKEN: ${{ github.token }}

    - name: Install Bicep (Nightly)
      if: env.USE_NIGHTLY == 'true' && runner.os != 'Windows'
      run: bash <(curl -Ls https://aka.ms/bicep/nightly-cli.sh) --binary-path ${{ runner.temp }}
      env:
        GH_TOKEN: ${{ github.token }}

    - name: Run tests (Nightly)
      if: env.USE_NIGHTLY == 'true'
      run: npm test
      env:
        BICEP_CLI_EXECUTABLE: ${{ runner.temp }}/bicep