name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: npm ci
      run: npm ci

    - name: Install Bicep Nightly
      run: bash <(curl -Ls https://aka.ms/bicep/nightly-cli.sh)
      env:
        GH_TOKEN: ${{ github.token }}

    - name: Run tests
      run: npm test
      env:
        BICEP_CLI_PATH: /home/runner/.azure/bin/bicep